In [90]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import(accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report)

In [92]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

In [94]:
print("Training data shape :",x_train.shape)
print("Testing data shape :",x_test.shape)

Training data shape : (60000, 28, 28)
Testing data shape : (10000, 28, 28)


In [96]:
x_train=x_train/255.0
x_test=x_test/255.0

In [98]:
model=tf.keras.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                           tf.keras.layers.Dense(128,activation='relu'),
                           tf.keras.layers.Dropout(0.2),
                           tf.keras.layers.Dense(10,activation='softmax')])
model.summary()
                          

C:\Users\BCA LAB 10\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_3 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [100]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [102]:
model.fit(x_train,y_train,epochs=10,batch_size=32,validation_split=0.1)

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9087 - loss: 0.3151 - val_accuracy: 0.9662 - val_loss: 0.1243
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9547 - loss: 0.1526 - val_accuracy: 0.9738 - val_loss: 0.0974
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9656 - loss: 0.1141 - val_accuracy: 0.9773 - val_loss: 0.0829
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9719 - loss: 0.0942 - val_accuracy: 0.9780 - val_loss: 0.0799
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9755 - loss: 0.0804 - val_accuracy: 0.9813 - val_loss: 0.0689
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9779 - loss: 0.0688 - val_accuracy: 0.9785 - val_loss: 0.0755
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9807 - loss: 0.0589 - val_accuracy: 0.9818 - val_loss: 0.0644
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9821 - loss: 0.0561 - 

In [103]:
loss,accuracy=model.evaluate(x_test,y_test,verbose=0)
print("loss :",loss)
print("Accuracy :",accuracy)

loss : 0.06974442303180695
Accuracy : 0.9799000024795532


In [104]:
y_probability=model.predict(x_test)
y_pred=np.argmax(y_probability,axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step


In [105]:
accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred,average='weighted')
recall=recall_score(y_test,y_pred,average='weighted')
f1=f1_score(y_test,y_pred,average='weighted')

In [106]:
print("\n---Performance Metrics---")
print("Accuracy :",accuracy)
print("Precision :",precision)
print("Recall :",recall)
print("F!_Score :",f1)


---Performance Metrics---
Accuracy : 0.9799
Precision : 0.9799678479786086
Recall : 0.9799
F!_Score : 0.9798765910714279


In [107]:
cm=confusion_matrix(y_test,y_pred)
print("\n---Confusion Matrix---")
print(cm)


---Confusion Matrix---
[[ 973    1    0    1    0    1    2    1    1    0]
 [   0 1126    4    1    0    0    2    0    2    0]
 [   6    0 1014    0    1    0    3    6    2    0]
 [   0    0    4  995    0    2    0    4    2    3]
 [   2    1    0    1  967    0    5    2    0    4]
 [   2    0    0    8    2  873    2    2    3    0]
 [   6    2    1    1    4    4  940    0    0    0]
 [   3    8    7    2    0    0    0 1003    1    4]
 [  11    3    3    5    4    8    4    4  928    4]
 [   4    5    0    3   10    1    0    5    1  980]]


In [ ]:
plt.figure(figsize=(8,6))
plt.imshow(cm,interpolation='nearest')
plt.title("Confusion Matrix")
plt.colorbar()
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks(np.arange(10),np.arange(10))
plt.yticks(np.arange(10),np.arange(10))
for i in range(10):
    for j in range(10):
        plt.text(j,i,cm[i,j],
                 ha='center',
                 va='center')
        plt.show()

In [112]:
print("\n---Classification Report---")
print(classification_report(y_test,y_pred,target_names=['Digit 0','Digit 1','Digit 2','Digit 3','Digit 4','Digit 5','Digit 6',
                                                        'Digit 7','Digit 8','Digit 9']))


---Classification Report---
              precision    recall  f1-score   support

     Digit 0       0.97      0.99      0.98       980
     Digit 1       0.98      0.99      0.99      1135
     Digit 2       0.98      0.98      0.98      1032
     Digit 3       0.98      0.99      0.98      1010
     Digit 4       0.98      0.98      0.98       982
     Digit 5       0.98      0.98      0.98       892
     Digit 6       0.98      0.98      0.98       958
     Digit 7       0.98      0.98      0.98      1028
     Digit 8       0.99      0.95      0.97       974
     Digit 9       0.98      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

